// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Artist struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Age  int    `json:"age"`
}

type NewArtist struct {
	Name string `json:"name"`
	Age  int    `json:"age"`
}

type NewSong struct {
	ArtistID     []string `json:"artistId"`
	Title        string   `json:"title"`
	Duration     float64  `json:"duration"`
	LyricsExists bool     `json:"lyricsExists"`
}

type Song struct {
	ID           string    `json:"id"`
	Title        string    `json:"title"`
	Duration     float64   `json:"duration"`
	LyricsExists bool      `json:"lyricsExists"`
	Artists      []*Artist `json:"artists"`
}
