// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ArtistsColumns holds the columns for the "artists" table.
	ArtistsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "age", Type: field.TypeInt},
	}
	// ArtistsTable holds the schema information for the "artists" table.
	ArtistsTable = &schema.Table{
		Name:       "artists",
		Columns:    ArtistsColumns,
		PrimaryKey: []*schema.Column{ArtistsColumns[0]},
	}
	// SongsColumns holds the columns for the "songs" table.
	SongsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "title", Type: field.TypeString},
		{Name: "duration", Type: field.TypeFloat64, SchemaType: map[string]string{"mysql": "decimal(6,2)"}},
		{Name: "lyrics_exits", Type: field.TypeBool, Default: false},
	}
	// SongsTable holds the schema information for the "songs" table.
	SongsTable = &schema.Table{
		Name:       "songs",
		Columns:    SongsColumns,
		PrimaryKey: []*schema.Column{SongsColumns[0]},
	}
	// ArtistSongsColumns holds the columns for the "artist_songs" table.
	ArtistSongsColumns = []*schema.Column{
		{Name: "artist_id", Type: field.TypeUUID},
		{Name: "song_id", Type: field.TypeUUID},
	}
	// ArtistSongsTable holds the schema information for the "artist_songs" table.
	ArtistSongsTable = &schema.Table{
		Name:       "artist_songs",
		Columns:    ArtistSongsColumns,
		PrimaryKey: []*schema.Column{ArtistSongsColumns[0], ArtistSongsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "artist_songs_artist_id",
				Columns:    []*schema.Column{ArtistSongsColumns[0]},
				RefColumns: []*schema.Column{ArtistsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "artist_songs_song_id",
				Columns:    []*schema.Column{ArtistSongsColumns[1]},
				RefColumns: []*schema.Column{SongsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ArtistsTable,
		SongsTable,
		ArtistSongsTable,
	}
)

func init() {
	ArtistSongsTable.ForeignKeys[0].RefTable = ArtistsTable
	ArtistSongsTable.ForeignKeys[1].RefTable = SongsTable
}
