// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/Zubayear/song-ql/ent/artist"
	"github.com/Zubayear/song-ql/ent/schema"
	"github.com/Zubayear/song-ql/ent/song"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	artistFields := schema.Artist{}.Fields()
	_ = artistFields
	// artistDescID is the schema descriptor for id field.
	artistDescID := artistFields[0].Descriptor()
	// artist.DefaultID holds the default value on creation for the id field.
	artist.DefaultID = artistDescID.Default.(func() uuid.UUID)
	songFields := schema.Song{}.Fields()
	_ = songFields
	// songDescLyricsExits is the schema descriptor for lyricsExits field.
	songDescLyricsExits := songFields[3].Descriptor()
	// song.DefaultLyricsExits holds the default value on creation for the lyricsExits field.
	song.DefaultLyricsExits = songDescLyricsExits.Default.(bool)
	// songDescID is the schema descriptor for id field.
	songDescID := songFields[0].Descriptor()
	// song.DefaultID holds the default value on creation for the id field.
	song.DefaultID = songDescID.Default.(func() uuid.UUID)
}
