// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/Zubayear/song-ql/graph"
	"github.com/Zubayear/song-ql/repository"
)

// Injectors from wire.go:

func DependencyProvider() (*graph.Resolver, error) {
	songRepository, err := repository.DatabaseImlProvider()
	if err != nil {
		return nil, err
	}
	resolver, err := graph.ResolverProvider(songRepository)
	if err != nil {
		return nil, err
	}
	return resolver, nil
}
