// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	ent "github.com/Zubayear/song-ql/ent"
	mock "github.com/stretchr/testify/mock"
)

// artistOption is an autogenerated mock type for the artistOption type
type artistOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *artistOption) Execute(_a0 *ent.ArtistMutation) {
	_m.Called(_a0)
}
