// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	ent "github.com/Zubayear/song-ql/ent"
	mock "github.com/stretchr/testify/mock"
)

// songOption is an autogenerated mock type for the songOption type
type songOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *songOption) Execute(_a0 *ent.SongMutation) {
	_m.Called(_a0)
}
